# Generated by Django 4.0.6 on 2023-04-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediareaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediareaction',
            name='id_mreaction',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
