# Generated by Django 4.1.7 on 2023-04-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_alter_user_id_user_alter_user_is_vip"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryMedia",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("id_media", models.IntegerField()),
                ("type_media", models.IntegerField()),
                ("day_watch", models.DateTimeField()),
                ("duration", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
