# Generated by Django 4.1.7 on 2023-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historymedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historymedia",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
