# Generated by Django 4.1.7 on 2023-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historymedia", "0002_alter_historymedia_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historymedia",
            name="id_media",
            field=models.CharField(max_length=200),
        ),
    ]
