# Generated by Django 4.1.7 on 2023-04-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channelfollow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelfollow",
            name="id_channel",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
