# Generated by Django 4.1.7 on 2023-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_is_vip_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_user",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_vip",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
