# Generated by Django 4.0.6 on 2023-04-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id_user'),
        ('user', '0003_alter_user_id_user_alter_user_is_vip'),
    ]

    operations = [
    ]
